"""empty message

Revision ID: 24e47bafec52
Revises: cf68ac7f5c17
Create Date: 2022-11-01 19:52:16.952268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e47bafec52'
down_revision = 'cf68ac7f5c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_report_user_date', table_name='report_user')
    op.drop_table('report_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('jobTitle', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answerForum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('online', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('add_online', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bonus', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['jobTitle'], ['role.id'], name='report_user_jobTitle_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='report_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='report_user_pkey')
    )
    op.create_index('ix_report_user_date', 'report_user', ['date'], unique=False)
    # ### end Alembic commands ###
