"""empty message

Revision ID: 285240643ca1
Revises: 56e61ae270c7
Create Date: 2022-11-02 13:04:57.569260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285240643ca1'
down_revision = '56e61ae270c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_user', sa.Column('week_balance', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('week_user', 'week_balance')
    # ### end Alembic commands ###
