"""empty message

Revision ID: 2e19317d2267
Revises: ddc6ae1f627e
Create Date: 2022-10-29 16:41:58.848638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e19317d2267'
down_revision = 'ddc6ae1f627e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date1', sa.String(length=10), nullable=True),
    sa.Column('date2', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jobTitle', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('answerForum', sa.Integer(), nullable=True),
    sa.Column('online', sa.Integer(), nullable=True),
    sa.Column('add_online', sa.Integer(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jobTitle'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_user_date1'), 'report_user', ['date1'], unique=False)
    op.create_index(op.f('ix_report_user_date2'), 'report_user', ['date2'], unique=False)
    op.drop_constraint('app_logs_user_id_fkey', 'app_logs', type_='foreignkey')
    op.drop_column('app_logs', 'user_id')
    op.add_column('role', sa.Column('viewName', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'role', ['viewName'])
    op.add_column('user', sa.Column('max_role', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['discord_id'])
    op.create_foreign_key(None, 'user', 'role', ['max_role'], ['id'])
    op.drop_column('user', 'currentWeekSalary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('currentWeekSalary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'max_role')
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'viewName')
    op.add_column('app_logs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('app_logs_user_id_fkey', 'app_logs', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_report_user_date2'), table_name='report_user')
    op.drop_index(op.f('ix_report_user_date1'), table_name='report_user')
    op.drop_table('report_user')
    # ### end Alembic commands ###
