"""empty message

Revision ID: 56e61ae270c7
Revises: 7a4335a514bf
Create Date: 2022-11-02 12:40:39.815316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e61ae270c7'
down_revision = '7a4335a514bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('week_user_report_id_fkey', 'week_user', type_='foreignkey')
    op.create_foreign_key(None, 'week_user', 'report', ['report_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'week_user', type_='foreignkey')
    op.create_foreign_key('week_user_report_id_fkey', 'week_user', 'report', ['report_id'], ['id'])
    # ### end Alembic commands ###
