"""empty message

Revision ID: 5e61ee59ca99
Revises: 2e19317d2267
Create Date: 2022-10-29 16:42:36.616337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e61ee59ca99'
down_revision = '2e19317d2267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_max_role_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'max_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('max_role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_max_role_fkey', 'user', 'role', ['max_role'], ['id'])
    # ### end Alembic commands ###
