"""empty message

Revision ID: 895d126a1f7d
Revises: 5e61ee59ca99
Create Date: 2022-10-29 16:56:51.494921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895d126a1f7d'
down_revision = '5e61ee59ca99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_user', sa.Column('date', sa.String(length=10), nullable=True))
    op.drop_index('ix_report_user_date1', table_name='report_user')
    op.drop_index('ix_report_user_date2', table_name='report_user')
    op.create_index(op.f('ix_report_user_date'), 'report_user', ['date'], unique=False)
    op.drop_column('report_user', 'salary')
    op.drop_column('report_user', 'balance')
    op.drop_column('report_user', 'date2')
    op.drop_column('report_user', 'date1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_user', sa.Column('date1', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('report_user', sa.Column('date2', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('report_user', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report_user', sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_report_user_date'), table_name='report_user')
    op.create_index('ix_report_user_date2', 'report_user', ['date2'], unique=False)
    op.create_index('ix_report_user_date1', 'report_user', ['date1'], unique=False)
    op.drop_column('report_user', 'date')
    # ### end Alembic commands ###
