"""empty message

Revision ID: 8e72f319e316
Revises: 4dc02c06009e
Create Date: 2022-11-03 23:18:55.252365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e72f319e316'
down_revision = '4dc02c06009e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_shop', sa.Column('viewName', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_shop', 'viewName')
    # ### end Alembic commands ###
