"""empty message

Revision ID: d4582a256b57
Revises: 895d126a1f7d
Create Date: 2022-10-29 17:16:50.556418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4582a256b57'
down_revision = '895d126a1f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line', sa.Column('serverLogs_id', sa.Integer(), nullable=True))
    op.drop_constraint('line_server_logs_id_fkey', 'line', type_='foreignkey')
    op.create_foreign_key(None, 'line', 'server_logs', ['serverLogs_id'], ['id'])
    op.drop_column('line', 'server_logs_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line', sa.Column('server_logs_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'line', type_='foreignkey')
    op.create_foreign_key('line_server_logs_id_fkey', 'line', 'server_logs', ['server_logs_id'], ['id'])
    op.drop_column('line', 'serverLogs_id')
    # ### end Alembic commands ###
