"""empty message

Revision ID: e1cfceba4356
Revises: 7b919d8bc42b
Create Date: 2022-11-04 14:00:57.592742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cfceba4356'
down_revision = '7b919d8bc42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('history_buy_item_id_fkey', 'history_buy', type_='foreignkey')
    op.create_foreign_key(None, 'history_buy', 'item_shop', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history_buy', type_='foreignkey')
    op.create_foreign_key('history_buy_item_id_fkey', 'history_buy', 'item_shop', ['item_id'], ['id'])
    # ### end Alembic commands ###
