"""empty message

Revision ID: e71f76be6b52
Revises: 3d39e51bf66a
Create Date: 2022-10-30 13:18:54.935695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e71f76be6b52'
down_revision = '3d39e51bf66a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dt_role_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('tmrpg_role_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_dt_role_fkey', 'user', type_='foreignkey')
    op.drop_constraint('user_tmrpg_role_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['tmrpg_role_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['dt_role_id'], ['id'])
    op.drop_column('user', 'dt_role')
    op.drop_column('user', 'tmrpg_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tmrpg_role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('dt_role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_tmrpg_role_fkey', 'user', 'role', ['tmrpg_role'], ['id'])
    op.create_foreign_key('user_dt_role_fkey', 'user', 'role', ['dt_role'], ['id'])
    op.drop_column('user', 'tmrpg_role_id')
    op.drop_column('user', 'dt_role_id')
    # ### end Alembic commands ###
